; -----------------------------------------------------
; DONT CHANGE THIS FILE - all modifieds will be lost.  
; -----------------------------------------------------
TEST_LBA       equ 0
BOOT2_LBA     equ  577   ; start LBA  BOOT2
BOOT2_SECTORS equ  1   ; 2048 *  1
; -----------------------------------------------------
KERNEL_LBA     equ  552   ; start LBA  KERNEL
KERNEL_SECTORS equ  25   ; 2048 *  25
; -----------------------------------------------------
VBE_INFO_ADDR   equ 0x0A00
