; -----------------------------------------------------
; DONT CHANGE THIS FILE - all modifieds will be lost.  
; -----------------------------------------------------
TEST_LBA       equ 0
BOOT2_LBA     equ  2629   ; start LBA  BOOT2
BOOT2_SECTORS equ  3   ; 2048 *  3
; -----------------------------------------------------
KERNEL_LBA     equ  552   ; start LBA  KERNEL
KERNEL_SECTORS equ  2077   ; 2048 *  2077
; -----------------------------------------------------
VBE_INFO_ADDR   equ 0x0A00
