; -----------------------------------------------------
; DONT CHANGE THIS FILE - all modifieds will be lost.  
; -----------------------------------------------------
TEST_LBA       equ 0
BOOT2_LBA     equ  67   ; start LBA  BOOT2
BOOT2_SECTORS equ  1   ; 2048 *  1
; -----------------------------------------------------
KERNEL_LBA     equ  35   ; start LBA  KERNEL
KERNEL_SECTORS equ  16   ; 2048 *  16
; -----------------------------------------------------
VBE_INFO_ADDR   equ 0x0A00
